Improved script.

diff --git a/src/system-info.d/18-neat b/src/system-info.d/18-neat
--- a/src/system-info.d/18-neat
+++ b/src/system-info.d/18-neat
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
-# Print system information
-# Copyright (C) 2013-2024 by Thomas Dreibholz
+# NEAT System-Info system-info.d Script
+# Copyright (C) 2013-2025 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,51 +16,26 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-# Contact: dreibh@simula.no
+# Contact: thomas.dreibholz@gmail.com
 
+# Bash options:
+set -eu
 
-# ###### Center text in console #############################################
-center ()
-{
-   local text="$1"
-   local length=${#text}
-   local width=`tput cols`   # Console width
-
-   let indent=(${width} - ${length})/2
-   if [ ${indent} -lt 0 ] ; then
-      indent=0
-   fi
-   printf "%${indent}s%s\n" "" "${text}"
-}
-
-
-# ###### Print centered separator in console ################################
-separator ()
-{
-   local separatorCharacter="="
-   local separator=""
-   local width=`tput cols`   # Console width
-   local separatorWidth
-
-   let separatorWidth=${width}-4
-   local i=0
-   while [ $i -lt ${separatorWidth} ] ; do
-      separator="${separator}${separatorCharacter}"
-      let i=$i+1
-   done
-   center "${separator}"
-}
+# Helper function library -> just return when it is not available.
+# Exit code 0 will let System-Info continue with the next script!
+# shellcheck disable=SC1091
+. "$(dirname "$0")/banner-helper" || exit 0
 
 
 # ====== Print banner =======================================================
 
 NEAT_STUFF_VERSION=""
 if [ -e /etc/neat/neat-stuff-version ] ; then
-   NEAT_STUFF_VERSION=`cat /etc/neat/neat-stuff-version`
+   NEAT_STUFF_VERSION="$(cat /etc/neat/neat-stuff-version)"
 fi
 
 echo -en "\x1b[1;34m"
-separator
+separator "  " "=" "  "
 echo -en "\x1b[1;31m"
 center "#     # #######    #    #######"
 center "##    # #         # #      #   "
@@ -76,7 +51,7 @@ if [ "${NEAT_STUFF_VERSION}" != "" ] ; then
    echo ""
    center "${NEAT_STUFF_VERSION}"
 fi
-separator
+separator "  " "=" "  "
 echo -e "\x1b[0m"
 
 
